export const SET_LANGUAGE = 'core/SET_LANGUAGE';
export const REFRESH_WINDOW_DIMENSIONS = 'core/REFRESH_WINDOW_DIMENSIONS';
export const FADE_ROUTE = 'core/FADE_ROUTE';
export const FINISH_FADING_ROUTE = 'core/FINISH_FADING_ROUTE';